### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by fancn21th** [fancn21th/mimic#12]
something like https://ant.design/docs/react/contributing-cn

**Comment by asiyeaili** [comment]
# 贡献指南

这篇指南会指导你如何为 mimic 贡献一份自己的力量，请在你要提 issue 或者 pull request 之前花几分钟来阅读一遍这篇指南。

### 行为规则

 [code of conduct](https://github.com/fancn21th/mimic/pull/20)（ 此处 code of conduct为 链接）作为行为规范，我们希望参与项目的各位严格遵守。请阅读 [全文](https://github.com/fancn21th/mimic/pull/20)去了解什么行为允许，什么行为不允许。 

### 人人皆可开发

mimic 项目在 [GitHub](https://github.com/fancn21th/mimic)上完成，核心团队及其以外的贡献者发送 pull requests，其代码评审流程皆为一致。

 ### 分支管理

请直接提交你的变更至 [main branch](https://github.com/fancn21th/mimic/tree/main)。对于开发或即将推出的版本，我们不会另建分支。我们尽力保持 `main` 不出问题，并通过所有测试。

合并进入 `main` 的代码必须与最新稳定版本兼容，可以有额外特性，但不能有重大变更。我们应从 `main` 随时能发布新的次版本号。

### 提出变更

如果你想改变公开的 API，或者对实现有不小的变更，我们建议你[发起 issue](https://github.com/fancn21th/mimic/issues/new)，这会让我们先对你的提议达成一致，然后你再着手工作。

如果只是修复漏洞，你当然可以立即提交 pull request，不过我们还是建议先去提出 issue 来说明你修复了什么，这就对一种情况

来说就很方便：我们没有接受特定 bug 的修复但想跟进该 issue 的情况。

### 首个 Pull Request

在写第一个 Pull Request？你可以从这一系列视频中学习怎么做：

**[How to Contribute to an Open Source Project on GitHub](https://app.egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github)**

为了使你能够快速上手和熟悉贡献流程，我们这里有个列表 [good first issues](https://github.com/fancn21th/mimic/issues/19) 

，里面有相对没那么笼统的漏洞，从这开始是个不错的选择。

如果你想解决一个 issue，请确定检查了该 issue 下的评论以防有人正在处理它。如果目前没人在处理该 issue，那么请留下评论

去表明你想处理该 issue 以便其他人不会意外重复你的工作。

如果有人留言表明要处理该 issue 但是超过两周没有跟进，你可以接手工作，不过也应该留言说明。

### 提交 Pull Request

mimic 团队会关注所有的 pull request，我们会 review 以及合并你的代码，也有可能要求你做一些修改或者告诉你我们为什么不

能接受这样的修改。

在你发送 **Pull Request** 之前，请确认你是按照下面的步骤来做的：

1. 基于 正确的分支 做修改。

2. 在项目根目录下运行了 `npm install`。

   下面这个内容可以先不写，后面遇到了再写出对应的正确的方案

   > 在 Windows 10 开发环境下，如果出现 `gyp err! find vs msvs_version not set from command line or npm config`错误, 请在运行 `npm install` 前安装 [最新版 Python v3](https://www.python.org/downloads/) ， 并通过 [Visual Studio Installer](https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio?view=vs-2019#step-3---install-the-visual-studio-installer) 安装 **Desktop development with C++**。

3. 如果你修复了一个 bug 或者新增了一个功能，请确保写了相应的测试，这很重要。

4. 确认所有的测试都是通过的 `npm run test`。 小贴士：开发过程中可以用 `npm test -- --watch TestName` 来运行指定的测试。

5. 运行 `npm test -- -u` 来更新 [jest snapshot](http://facebook.github.io/jest/docs/en/snapshot-testing.html#snapshot-testing-with-jest)  并且把这些更新也提交上来（如果有的话）。

6. 确认所有的 UI 改动通过 `npm run test-image`，可以运行 `npm run test-image -- -u` 更新 UI 快照并且把这些更新也提交上来（如果有的话），UI 测试基于 [Docker](https://docs.docker.com/get-docker/)，根据平台下载对应的安装程序。

7. 确保你的代码通过了 lint 检查 `npm run lint`. 小贴士: Lint 会在你 `git commit` 的时候自动运行（通过[Git Hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks)

给 [react-component](https://github.com/react-component/)发送 pull request：

### 贡献者许可证协议

为了让你的 pull request 得到接受，你得提交贡献者许可证协议。你只需提交该协议一次，所以如果你曾经对另一个 mimic 开源

项目提交过，那么你已经准备好了。如果你是第一次提交 pull request，请让我们得知你已提交协议，这样我们能多方核对你的 

GitHub 用户名。

**[请在这里签订贡献者许可证协议](https://code.facebook.com/cla)**

### 可接受的贡献者

这个包的用途作为一个节点包真的是无用的。我创建它是为了演示如何为开源项目做出贡献。但是，我仍然有标准！我只接受以

下拉取请求：

- 修复现有函数的错误
- 增强 API 或现有函数的实现
- 添加一个仅从 StackOverflow 答案稍作修改的函数
- 经过测试

在添加新函数的情况下，该函数必须：

- 不要向内置对象的原型添加任何内容（StackOverflow最喜欢的事情之一）
- 导出到文件中`src/index.js`
- 原始来源来源的文档

所有代码都必须遵循 ESLint 规定的样式。只要你不跳过git钩子，你就不需要担心错过一些东西。

另外，在处理PR之前，**请讨论问题中的任何更改**，以确保在您花时间处理它之前我会接受它。

### 开发工作流程

克隆 mimic 项目后，执行 `npm install` 来获取依赖。 之后，你可以执行以下命令：

- `npm run  test` 运行完整的测试套装。

  (  `npm run test --watch` 运行交互式的测试监听器  )

- `npm build` 新建涉及所有包的 `build` 文件夹。

- `npm run commit`  ： commit 到本地

- `git push` : 提交到本地库上

- 最后管理员把你所写的内容review 以后 ,你再手动点击 Commit Pull Request 就可以了

**Comment by asiyeaili** [comment]
好的

**Comment by embermeng** [comment]
之前提了几个改进的建议，现在看已经改好了
