### ISSUE TITLE
Contributor Covenant Code of Conduct

### ISSUE THREAD

**Issue by fancn21th** [fancn21th/mimic#13]
something like https://github.com/ant-design/ant-design/blob/master/CODE_OF_CONDUCT.md

**Comment by zlxiao97** [comment]
### 添加一个贡献者行为准则文档
**目的**

- 明确贡献者的行为规范
- 营造一个开放、热情的开源环境

**文档涉及以下内容**

- 我们的承诺
- 我们的标准
- 我们的责任
- 适用范围
- 举报方式
- 来源

**Comment by fancn21th** [comment]
看上去不错，请发个 PR看看
